// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Kind of video source being extracted from.
enum SourceKind { asset, file, network }

/// A single extraction request.
///
/// The native side must decode one frame per the fields below and encode it
/// directly into [destPath] (a `.part` file chosen by the Dart engine). It
/// must never buffer the encoded image in memory for return.
class ExtractRequest {
  ExtractRequest({
    required this.requestId,
    required this.sourceType,
    required this.source,
    this.assetPackage,
    this.headers,
    required this.positionMs,
    required this.exact,
    required this.maxWidth,
    required this.maxHeight,
    required this.format,
    required this.quality,
    required this.destPath,
  });

  /// Engine-unique id; used for native-side cancellation on iOS.
  String requestId;

  SourceKind sourceType;

  /// Asset key, absolute file path, or http(s) URL depending on [sourceType].
  String source;

  /// Package name for package-relative assets.
  String? assetPackage;

  /// Optional HTTP headers for network sources.
  Map<String, String>? headers;

  /// Desired frame position in milliseconds. Natives clamp into the duration.
  int positionMs;

  /// false: nearest sync/key frame (fast). true: exact frame (slow).
  bool exact;

  /// Fit-within box in pixels. 0 means unconstrained on that axis.
  /// Aspect ratio is always preserved; frames are never upscaled.
  int maxWidth;

  int maxHeight;

  /// 'jpeg' or 'png'.
  String format;

  /// 1..100. Ignored for png.
  int quality;

  /// Absolute path of the temp file the native side writes the encoded image to.
  String destPath;

  List<Object?> _toList() {
    return <Object?>[
      requestId,
      sourceType,
      source,
      assetPackage,
      headers,
      positionMs,
      exact,
      maxWidth,
      maxHeight,
      format,
      quality,
      destPath,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ExtractRequest decode(Object result) {
    result as List<Object?>;
    return ExtractRequest(
      requestId: result[0]! as String,
      sourceType: result[1]! as SourceKind,
      source: result[2]! as String,
      assetPackage: result[3] as String?,
      headers: (result[4] as Map<Object?, Object?>?)?.cast<String, String>(),
      positionMs: result[5]! as int,
      exact: result[6]! as bool,
      maxWidth: result[7]! as int,
      maxHeight: result[8]! as int,
      format: result[9]! as String,
      quality: result[10]! as int,
      destPath: result[11]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExtractRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(requestId, other.requestId) &&
        _deepEquals(sourceType, other.sourceType) &&
        _deepEquals(source, other.source) &&
        _deepEquals(assetPackage, other.assetPackage) &&
        _deepEquals(headers, other.headers) &&
        _deepEquals(positionMs, other.positionMs) &&
        _deepEquals(exact, other.exact) &&
        _deepEquals(maxWidth, other.maxWidth) &&
        _deepEquals(maxHeight, other.maxHeight) &&
        _deepEquals(format, other.format) &&
        _deepEquals(quality, other.quality) &&
        _deepEquals(destPath, other.destPath);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExtractRequest(requestId: $requestId, sourceType: $sourceType, source: $source, assetPackage: $assetPackage, headers: $headers, positionMs: $positionMs, exact: $exact, maxWidth: $maxWidth, maxHeight: $maxHeight, format: $format, quality: $quality, destPath: $destPath)';
  }
}

/// Result of a successful extraction: the encoded image dimensions.
class ExtractResult {
  ExtractResult({required this.width, required this.height});

  int width;

  int height;

  List<Object?> _toList() {
    return <Object?>[width, height];
  }

  Object encode() {
    return _toList();
  }

  static ExtractResult decode(Object result) {
    result as List<Object?>;
    return ExtractResult(width: result[0]! as int, height: result[1]! as int);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExtractResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExtractResult(width: $width, height: $height)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is SourceKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is ExtractRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is ExtractResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : SourceKind.values[value];
      case 130:
        return ExtractRequest.decode(readValue(buffer)!);
      case 131:
        return ExtractResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ThumbnailHostApi {
  /// Constructor for [ThumbnailHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ThumbnailHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Extracts one frame and encodes it into `request.destPath`.
  ///
  /// Errors are surfaced as `PlatformException` whose `code` is one of:
  /// invalidSource, assetNotFound, fileNotFound, network, unsupportedMedia,
  /// extractionFailed, encodingFailed, io, cancelled.
  Future<ExtractResult> extract(ExtractRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.thumbnail.ThumbnailHostApi.extract$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as ExtractResult;
  }

  /// Best-effort cancellation of an in-flight extraction (iOS only in v1).
  Future<void> cancel(String requestId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.thumbnail.ThumbnailHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[requestId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
