// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package tech.tomars.cached_video_thumbnail

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Kind of video source being extracted from. */
enum class SourceKind(val raw: Int) {
  ASSET(0),
  FILE(1),
  NETWORK(2);

  companion object {
    fun ofRaw(raw: Int): SourceKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A single extraction request.
 *
 * The native side must decode one frame per the fields below and encode it
 * directly into [destPath] (a `.part` file chosen by the Dart engine). It
 * must never buffer the encoded image in memory for return.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ExtractRequest (
  /** Engine-unique id; used for native-side cancellation on iOS. */
  val requestId: String,
  val sourceType: SourceKind,
  /** Asset key, absolute file path, or http(s) URL depending on [sourceType]. */
  val source: String,
  /** Package name for package-relative assets. */
  val assetPackage: String? = null,
  /** Optional HTTP headers for network sources. */
  val headers: Map<String, String>? = null,
  /** Desired frame position in milliseconds. Natives clamp into the duration. */
  val positionMs: Long,
  /** false: nearest sync/key frame (fast). true: exact frame (slow). */
  val exact: Boolean,
  /**
   * Fit-within box in pixels. 0 means unconstrained on that axis.
   * Aspect ratio is always preserved; frames are never upscaled.
   */
  val maxWidth: Long,
  val maxHeight: Long,
  /** 'jpeg' or 'png'. */
  val format: String,
  /** 1..100. Ignored for png. */
  val quality: Long,
  /** Absolute path of the temp file the native side writes the encoded image to. */
  val destPath: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExtractRequest {
      val requestId = pigeonVar_list[0] as String
      val sourceType = pigeonVar_list[1] as SourceKind
      val source = pigeonVar_list[2] as String
      val assetPackage = pigeonVar_list[3] as String?
      val headers = pigeonVar_list[4] as Map<String, String>?
      val positionMs = pigeonVar_list[5] as Long
      val exact = pigeonVar_list[6] as Boolean
      val maxWidth = pigeonVar_list[7] as Long
      val maxHeight = pigeonVar_list[8] as Long
      val format = pigeonVar_list[9] as String
      val quality = pigeonVar_list[10] as Long
      val destPath = pigeonVar_list[11] as String
      return ExtractRequest(requestId, sourceType, source, assetPackage, headers, positionMs, exact, maxWidth, maxHeight, format, quality, destPath)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      sourceType,
      source,
      assetPackage,
      headers,
      positionMs,
      exact,
      maxWidth,
      maxHeight,
      format,
      quality,
      destPath,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExtractRequest
    return MessagesPigeonUtils.deepEquals(this.requestId, other.requestId) && MessagesPigeonUtils.deepEquals(this.sourceType, other.sourceType) && MessagesPigeonUtils.deepEquals(this.source, other.source) && MessagesPigeonUtils.deepEquals(this.assetPackage, other.assetPackage) && MessagesPigeonUtils.deepEquals(this.headers, other.headers) && MessagesPigeonUtils.deepEquals(this.positionMs, other.positionMs) && MessagesPigeonUtils.deepEquals(this.exact, other.exact) && MessagesPigeonUtils.deepEquals(this.maxWidth, other.maxWidth) && MessagesPigeonUtils.deepEquals(this.maxHeight, other.maxHeight) && MessagesPigeonUtils.deepEquals(this.format, other.format) && MessagesPigeonUtils.deepEquals(this.quality, other.quality) && MessagesPigeonUtils.deepEquals(this.destPath, other.destPath)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.requestId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourceType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.source)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.assetPackage)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.headers)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.positionMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.exact)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxWidth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxHeight)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.format)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.quality)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.destPath)
    return result
  }
  override fun toString(): String {
    return "ExtractRequest(requestId=$requestId, sourceType=$sourceType, source=$source, assetPackage=$assetPackage, headers=$headers, positionMs=$positionMs, exact=$exact, maxWidth=$maxWidth, maxHeight=$maxHeight, format=$format, quality=$quality, destPath=$destPath)"
  }
}

/**
 * Result of a successful extraction: the encoded image dimensions.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ExtractResult (
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExtractResult {
      val width = pigeonVar_list[0] as Long
      val height = pigeonVar_list[1] as Long
      return ExtractResult(width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExtractResult
    return MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    return result
  }
  override fun toString(): String {
    return "ExtractResult(width=$width, height=$height)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SourceKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExtractRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExtractResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SourceKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ExtractRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ExtractResult -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ThumbnailHostApi {
  /**
   * Extracts one frame and encodes it into `request.destPath`.
   *
   * Errors are surfaced as `PlatformException` whose `code` is one of:
   * invalidSource, assetNotFound, fileNotFound, network, unsupportedMedia,
   * extractionFailed, encodingFailed, io, cancelled.
   */
  fun extract(request: ExtractRequest, callback: (Result<ExtractResult>) -> Unit)
  /** Best-effort cancellation of an in-flight extraction (iOS only in v1). */
  fun cancel(requestId: String)

  companion object {
    /** The codec used by ThumbnailHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ThumbnailHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ThumbnailHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cached_video_thumbnail.ThumbnailHostApi.extract$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ExtractRequest
            api.extract(requestArg) { result: Result<ExtractResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cached_video_thumbnail.ThumbnailHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancel(requestIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
