// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum messagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Kind of video source being extracted from.
enum SourceKind: Int, CaseIterable {
  case asset = 0
  case file = 1
  case network = 2
}

/// A single extraction request.
///
/// The native side must decode one frame per the fields below and encode it
/// directly into [destPath] (a `.part` file chosen by the Dart engine). It
/// must never buffer the encoded image in memory for return.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ExtractRequest: Hashable, CustomStringConvertible {
  /// Engine-unique id; used for native-side cancellation on iOS.
  var requestId: String
  var sourceType: SourceKind
  /// Asset key, absolute file path, or http(s) URL depending on [sourceType].
  var source: String
  /// Package name for package-relative assets.
  var assetPackage: String? = nil
  /// Optional HTTP headers for network sources.
  var headers: [String: String]? = nil
  /// Desired frame position in milliseconds. Natives clamp into the duration.
  var positionMs: Int64
  /// false: nearest sync/key frame (fast). true: exact frame (slow).
  var exact: Bool
  /// Fit-within box in pixels. 0 means unconstrained on that axis.
  /// Aspect ratio is always preserved; frames are never upscaled.
  var maxWidth: Int64
  var maxHeight: Int64
  /// 'jpeg' or 'png'.
  var format: String
  /// 1..100. Ignored for png.
  var quality: Int64
  /// Absolute path of the temp file the native side writes the encoded image to.
  var destPath: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ExtractRequest? {
    let requestId = pigeonVar_list[0] as! String
    let sourceType = pigeonVar_list[1] as! SourceKind
    let source = pigeonVar_list[2] as! String
    let assetPackage: String? = nilOrValue(pigeonVar_list[3])
    let headers: [String: String]? = nilOrValue(pigeonVar_list[4])
    let positionMs = pigeonVar_list[5] as! Int64
    let exact = pigeonVar_list[6] as! Bool
    let maxWidth = pigeonVar_list[7] as! Int64
    let maxHeight = pigeonVar_list[8] as! Int64
    let format = pigeonVar_list[9] as! String
    let quality = pigeonVar_list[10] as! Int64
    let destPath = pigeonVar_list[11] as! String

    return ExtractRequest(
      requestId: requestId,
      sourceType: sourceType,
      source: source,
      assetPackage: assetPackage,
      headers: headers,
      positionMs: positionMs,
      exact: exact,
      maxWidth: maxWidth,
      maxHeight: maxHeight,
      format: format,
      quality: quality,
      destPath: destPath
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      sourceType,
      source,
      assetPackage,
      headers,
      positionMs,
      exact,
      maxWidth,
      maxHeight,
      format,
      quality,
      destPath,
    ]
  }
  static func == (lhs: ExtractRequest, rhs: ExtractRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.requestId, rhs.requestId) && messagesPigeonInternal.deepEquals(lhs.sourceType, rhs.sourceType) && messagesPigeonInternal.deepEquals(lhs.source, rhs.source) && messagesPigeonInternal.deepEquals(lhs.assetPackage, rhs.assetPackage) && messagesPigeonInternal.deepEquals(lhs.headers, rhs.headers) && messagesPigeonInternal.deepEquals(lhs.positionMs, rhs.positionMs) && messagesPigeonInternal.deepEquals(lhs.exact, rhs.exact) && messagesPigeonInternal.deepEquals(lhs.maxWidth, rhs.maxWidth) && messagesPigeonInternal.deepEquals(lhs.maxHeight, rhs.maxHeight) && messagesPigeonInternal.deepEquals(lhs.format, rhs.format) && messagesPigeonInternal.deepEquals(lhs.quality, rhs.quality) && messagesPigeonInternal.deepEquals(lhs.destPath, rhs.destPath)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ExtractRequest")
    messagesPigeonInternal.deepHash(value: requestId, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: sourceType, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: source, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: assetPackage, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: headers, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: positionMs, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: exact, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: maxWidth, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: maxHeight, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: format, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: quality, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: destPath, hasher: &hasher)
  }

  public var description: String {
    return "ExtractRequest(requestId: \(String(describing: requestId)), sourceType: \(String(describing: sourceType)), source: \(String(describing: source)), assetPackage: \(String(describing: assetPackage)), headers: \(String(describing: headers)), positionMs: \(String(describing: positionMs)), exact: \(String(describing: exact)), maxWidth: \(String(describing: maxWidth)), maxHeight: \(String(describing: maxHeight)), format: \(String(describing: format)), quality: \(String(describing: quality)), destPath: \(String(describing: destPath)))"
  }
}

/// Result of a successful extraction: the encoded image dimensions.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ExtractResult: Hashable, CustomStringConvertible {
  var width: Int64
  var height: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ExtractResult? {
    let width = pigeonVar_list[0] as! Int64
    let height = pigeonVar_list[1] as! Int64

    return ExtractResult(
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
    ]
  }
  static func == (lhs: ExtractResult, rhs: ExtractResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.width, rhs.width) && messagesPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ExtractResult")
    messagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "ExtractResult(width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SourceKind(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return ExtractRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return ExtractResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SourceKind {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ExtractRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? ExtractResult {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ThumbnailHostApi {
  /// Extracts one frame and encodes it into `request.destPath`.
  ///
  /// Errors are surfaced as `PlatformException` whose `code` is one of:
  /// invalidSource, assetNotFound, fileNotFound, network, unsupportedMedia,
  /// extractionFailed, encodingFailed, io, cancelled.
  func extract(request: ExtractRequest, completion: @escaping (Result<ExtractResult, Error>) -> Void)
  /// Best-effort cancellation of an in-flight extraction (iOS only in v1).
  func cancel(requestId: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ThumbnailHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ThumbnailHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ThumbnailHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Extracts one frame and encodes it into `request.destPath`.
    ///
    /// Errors are surfaced as `PlatformException` whose `code` is one of:
    /// invalidSource, assetNotFound, fileNotFound, network, unsupportedMedia,
    /// extractionFailed, encodingFailed, io, cancelled.
    let extractChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cached_video_thumbnail.ThumbnailHostApi.extract\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      extractChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ExtractRequest
        api.extract(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      extractChannel.setMessageHandler(nil)
    }
    /// Best-effort cancellation of an in-flight extraction (iOS only in v1).
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cached_video_thumbnail.ThumbnailHostApi.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        do {
          try api.cancel(requestId: requestIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
  }
}
